### ISSUE TITLE
[TextButton] data-automation-id is duplicated in TextButton component

### ISSUE THREAD

**Issue by neilpelow** [Workday/canvas-kit#515] opened 2020-03-13 16:14 UTC
`<button
            class="css-18o54oi ecfc8xq0"
            data-automation-id="propertyDataGrid-addButton"
          >
            <span
              class="css-v7sueo ee73cc41"
              data-automation-id="propertyDataGrid-addButton"
            >
              + Add Another Value
            </span>
          </button>`

data-automation-id is duplicated in `div` and in `span`

`<TextButton
          buttonType={TextButtonTypes.Default}
          buttonSize={ButtonSizes.Small}
          onClick={this.onItemAdded}
          className={addButtonStyle}
          data-automation-id={testIds.addButton}
        >
          + Add Another Value
        </TextButton>` 

See component used in client project above. Issue does not seem to persist with other canvas button types.

**Comment by anicholls** [comment] 2020-03-13 16:43
@neilpelow This is a problem with an older version of `TextButton` (made obvious by the old props `buttonType` and `buttonSize`). It is working as intended on master. It was likely fixed in https://github.com/Workday/canvas-kit/pull/129 as part of a button refactor in preparation for v3.0. 

You can fix by updating your Canvas Kit dependencies

**Closed by anicholls** 2020-03-13 16:43 UTC
Labels: bug, p:2
