### ISSUE TITLE
Combobox Text Input obscures nearby Combobox Menu

### ISSUE THREAD

**Issue by jamesfan** [Workday/canvas-kit#1122] opened 2021-06-22 18:28 UTC
## 🐛 Bug Report

In cases where multiple Comboboxes are displayed next to one another, the Text Input of one Combobox can obscure the Menu of another Combobox.

## To Reproduce

[Reproduction Codesandbox](https://codesandbox.io/s/combobox-zindex-5t5qm?file=/src/App.js).

Grant focus to the first/top Combobox. Note how its autocomplete Menu displays _underneath_ the Text Input of the second/bottom Combobox.

<img width="1368" alt="combobox-zindex-issue" src="https://user-images.githubusercontent.com/146020/122979656-abe7c300-d34c-11eb-83ee-8d77b5d8a6af.png">

## Expected Behavior

The Menu of the top Combobox should display _above_ the Text Input for the bottom Combobox.

**Comment by jamesfan** [comment] 2021-06-22 19:03
This is happening due to the `zIndex: 2` being applied to the Text Input [here](https://github.com/Workday/canvas-kit/blob/support/v4.x/modules/_labs/combobox/react/lib/Combobox.tsx#L409) (the Menu has a lower `zIndex: 1` defined [here](https://github.com/Workday/canvas-kit/blob/support/v4.x/modules/_labs/combobox/react/lib/Combobox.tsx#L98)). The `zIndex: 2` seems to have been added to prevent the Menu from obscuring the bottom edge of its corresponding Text Input. Disabling the `zIndex: 2` fixes the original issue, but results in the following odd visual:

<img width="1367" alt="combobox-remove-zindex" src="https://user-images.githubusercontent.com/146020/122980618-ba82aa00-d34d-11eb-8f9e-07c079d5f3f0.png">

The [reproduction Codesandbox](https://codesandbox.io/s/combobox-zindex-5t5qm?file=/src/App.js) includes a workaround for the original issue by applying `style={{position: 'relative', zIndex: 3}}` to the top FormField.

We should find a proper fix for this issue, consulting with Design to adjust the visuals of the component if necessary. It may be best to minimize our use of `zIndex` given how complicated it can be (see [stacking contexts](https://www.joshwcomeau.com/css/stacking-contexts/)). A relatively simple solution would be to move the Menu further down so it doesn't block any portion of its corresponding Text Input and focus ring:

<img width="1363" alt="combobox-move-menu" src="https://user-images.githubusercontent.com/146020/122982771-2239f480-d350-11eb-83ef-5eeab47fbb25.png">

**Comment by jaclynjessup** [comment] 2022-09-28 19:26
Dupe of #1668 which was fixed in #1752

**Closed by jaclynjessup** 2022-09-28 19:26 UTC
Labels: bug
