### ISSUE TITLE
First-Child Console Errors in Non Storybook Dev Environments

### ISSUE THREAD

**Issue by drschulz** [Workday/canvas-kit#373] opened 2019-12-13 20:10 UTC
## 🐛 Bug Report

When running our project locally with canvas, we are experiencing the following error:

`The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".`

We first went [here](https://github.com/Workday/canvas-kit/blob/master/modules/layout/react/lib/Column.tsx#L28) to find where `:first-child` was being used in canvas, because we're using the Layout component. Then we saw the emotion issue [here](https://github.com/emotion-js/emotion/issues/1105), and also saw a Pull Request from Alex [here](https://github.com/Workday/canvas-kit/pull/116). That pull request fixed console errors when running canvas through storybook, however these logs are still appearing in non storybook development environments (local react apps, code sandbox, etc.)

## To Reproduce

1. Place a Layout.Column component in a React component (https://codesandbox.io/s/late-wind-bzffm)

## Expected Behavior

No error should log regarding the `first-child` selector.

## Actual Results

The error log appears in all dev environments and unit test systems using canvas where the node environment is DEV.

### Error Output

```bash
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```

**Comment by drschulz** [comment] 2019-12-13 20:11
To add to this, it looks like the current solution from emotion is to use the comment:
```
/* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-
 the-warning-exists-for-a-reason */
```

But not sure how you guys wanted to handle this so I thought I'd make an issue instead of a PR.

**Comment by lychyi** [comment] 2020-03-03 18:30
Dupe of #90

**Closed by lychyi** 2020-03-03 18:30 UTC
Labels: bug
