### ISSUE TITLE
Icon Button does not retain focus in Firefox and Safari

### ISSUE THREAD

**Issue by amritbhullar** [Workday/canvas-kit#141] opened 2019-08-21 17:24 UTC
## 🐛 Bug Report

In Chrome, components utilizing the `IconButton` component retain a focus around the button when clicked on. However, in Firefox or Safari, the focus does not get retained when the button is clicked. Although focus is retained when focusing and clicking via keyboard on all browsers, it should retain focus via mouse click as well. 

## To Reproduce

- Open Storybook in Firefox or Safari
- Navigate to the `Button` > `Icon Button` > and click on the `Inverse Filled` story
- Click on any of the buttons to see the focus ring appear briefly, but focus gets lost

## Expected Behavior

When selecting the Icon Button via mouse click, expected behavior should be that focus does not get lost on the page and instead remains on the button that was clicked. Should work exactly as it does when selecting via Enter key. 

## Actual Results

When clicking the Icon Button via mouse, focus gets lost and instead the `body` of the page gets focus from my experience. 

## Browser (if applicable)

Mozilla Firefox and Safari

## Link to repl or repo (highly encouraged)

N/A

### Error Output

(Firefox example): 
![ezgif com-resize (1)](https://user-images.githubusercontent.com/32023876/63453564-ca51a000-c3fd-11e9-8901-76cdfc8d7ac8.gif)

**Comment by stephanerangaya** [comment] 2019-09-19 22:11
Thank you for bringing this issue to our attention! 

I looked into it and it turns out it is the normal focus behavior for the browsers you mentioned.

On Windows, all major browsers leave the focus on the buttons after a click, but on macOS, only Google Chrome and Opera do. On that platform, Mozilla Firefox and Apple Safari do not leave the focus on the buttons after a click.

You can see this by opening [this link](http://jsfiddle.net/hRub4/) in Chrome, Safari and Firefox on macOS and click on the button to see which browsers keep the focus after the click.

From these findings, I see two ways we could see this issue:
- we consider this as normal browser behavior and we do not try to add focus on buttons
- we use an anchor `a` element as a base HTML element instead of a button because anchor elements keep focus on all browsers (as long as they have a `tabindex`)

Any other potential solution/ideas of what we should do?

**Comment by anicholls** [comment] 2019-09-19 23:30
Since this is standard behavior for buttons in these browsers, my vote would be to keep the behavior as is and close the issue. When used with the `InputProvider` component (this example isn't), it would prevent the flash of the focus outline, which is the worst part of this anyway.

**Comment by lychyi** [comment] 2019-09-23 15:43
Internal a11y teams are weighing in and we'll close this issue as soon as we get confirmation that we can/should keep it this way.

Thanks for the detailed explanation @stephanerangaya

**Comment by lychyi** [comment] 2019-09-23 16:07
Resource: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by lychyi** [comment] 2019-09-24 15:42
@stephanerangaya @amritbhullar a11y confirmed that this is appropriate behavior and this issue is okay to close.

**Closed by lychyi** 2019-09-24 15:42 UTC
Labels: bug, p:1

**Comment by amritbhullar** [comment] 2019-09-24 20:56
Sounds good, thanks for the follow-up! :)
