### ISSUE TITLE
Create a lint rule to prevent local links in storybook examples

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#1239] opened 2021-08-27 00:20 UTC
## 🚀 Feature Proposal

Let's ensure [this](https://github.com/Workday/canvas-kit/pull/1238) doesn't happen anymore. We may also want to force named imports as a best practice in examples.

**Comment by jaclynjessup** [comment] 2022-10-05 19:35
Dupe of #1570

**Closed by jaclynjessup** 2022-10-05 19:35 UTC
