### ISSUE TITLE
Add icon support for DeleteButton

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2341] opened 2023-09-18 21:04 UTC
## 🚀 Feature Proposal

Add `icon` support to our `DeleteButton`.

- Add `iconPosition` prop
- Add the following code block:
```tsx
{icon && iconPosition === 'start' && (
          <BaseButton.Icon
            size={size}
            iconPosition={iconPosition}
            icon={icon}
            shouldMirrorIcon={shouldMirrorIcon}
          />
        )}
        {children && <BaseButton.Label>{children}</BaseButton.Label>}

        {icon && iconPosition === 'end' && (
          <BaseButton.Icon
            size={size}
            iconPosition={iconPosition}
            icon={icon}
            shouldMirrorIcon={shouldMirrorIcon}
          />
        )}
```
- Adjust the icon color based on spec
- Add storybook example and chromatic example

## Motivation
Make out buttons consistent as well as support for them.

**Comment by jaclynjessup** [comment] 2023-11-20 17:38
Duplicate of #2403

**Closed by jaclynjessup** 2023-11-20 17:38 UTC
Labels: 10.x
