### ISSUE TITLE
Broken Link in Code Style Guide

### ISSUE THREAD

**Issue by sarah-duncan** [Workday/canvas-kit#1566] opened 2022-05-04 10:52 UTC
## 🐛 Bug Report

There is a link in https://github.com/Workday/canvas-kit/blob/master/modules/docs/mdx/CONTRIBUTING.mdx#code-style-guide
called [API & Pattern Guidelines](https://github.com/Workday/canvas-kit/blob/master/getting-started/for-developers/resources/api-pattern-guidelines). that results in 404 error and presumably should point to https://github.com/Workday/canvas-kit/blob/master/modules/docs/mdx/API_PATTERN_GUIDELINES.mdx instead

## To Reproduce

Go to https://github.com/Workday/canvas-kit/blob/master/modules/docs/mdx/CONTRIBUTING.mdx#code-style-guide and click the link at API & Pattern Guidelines.
## Expected Behavior

The page should point to the API & Pattern Guidelines https://github.com/Workday/canvas-kit/blob/master/modules/docs/mdx/API_PATTERN_GUIDELINES.mdx instead
## Actual Results

A clear and concise description of what actually happens
Page not found error (404)
## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

Paste the error output here
Broken link: https://github.com/Workday/canvas-kit/blob/master/getting-started/for-developers/resources/api-pattern-guidelines

**Comment by myvuuu** [comment] 2022-05-05 20:16
A router (routes.js) should be used to link to https://canvas.workdaydesign.com/getting-started/for-developers/resources/api-pattern-guidelines

**Comment by willklein** [comment] 2022-05-23 18:43
Thanks for taking the time to log this issue, @sarah-duncan!

I just created #1602 to track a broader effort needed to improve our links. We can't implement the expected behavior because that would break both our [Storybook](https://workday.github.io/canvas-kit/) and the [Canvas site](https://canvas.workday.com/).

We should make those links functional though, even when accessing the source files on github.com, as this issue suggests. We need to do some prerequisite work to improve our redirects, routing, and also missing content, and then can point all of these links to URLs on the Canvas site.

While this issue is valid, I'm going to close it in favor of #1602 to better describe the effort we need to track. Thank you again!

**Closed by willklein** 2022-05-23 18:43 UTC
Labels: bug, p:2, documentation
