### ISSUE TITLE
Removal of `Menu` in preview

### ISSUE THREAD

**Issue by josh-bagwell** [Workday/canvas-kit#2188] opened 2023-05-02 19:45 UTC
## 🚀 Feature Proposal

Remove `Menu` in preview.

## Motivation

`Menu` in preview was deprecated in v8 and since we could not remove it in v9 with a codemod, a migration guide was created for users to move to `Menu` in main (Since this is the compound component version of `Menu`).

**Comment by jaclynjessup** [comment] 2023-05-12 17:25
dupe of #1993

**Closed by jaclynjessup** 2023-05-12 17:25 UTC
Labels: breaking-change, 10.x
