### ISSUE TITLE
Hover State For Icon Button Shows Hover State and Focus State

### ISSUE THREAD

**Issue by aurbanski** [Workday/canvas-kit#497] opened 2020-03-05 16:57 UTC
## 🐛 Bug Report

Talking to Mia Donnell, she brought up that canvas buttons should only hold the focus state when they are focused. But just importing the Icon Button without styling, the button on focus is showing a gray background which is indicative of hover in addition to the blue focus ring 
![image](https://user-images.githubusercontent.com/22889346/76004739-3b9eff00-5ec7-11ea-9f07-e5de0cf186ed.png)
Here's also a code snippet showing how it is being rendered 
![image](https://user-images.githubusercontent.com/22889346/76004833-612c0880-5ec7-11ea-8c67-0d19d28cfe7c.png)

## To Reproduce

Just click on the icon button

## Expected Behavior

The button should have a white background unless it is hovered on, while still maintaining the focus ring.

## Actual Results

The button always has the gray background indicative of hover while having the blue focus ring

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

Please provide a reference to a repo or branch to help us reproduce this bug.

### Error Output

Paste the error output here

```bash

```

or

Include a screenshot of a visual bug

**Comment by anicholls** [comment] 2020-03-05 17:47
@aurbanski This is behaving as intended. The majority of our focus styles also apply the hover styles (we see it as "hovering" with your keyboard haha). 

Just to clarify, your frustration is that the background is turning gray on focus? You expect that only the focus ring appears when you focus the button and that the gray background is specifically tied to mouse hover? In this case, the gray background would still appear while you're clicking on it to provide focus.

**Comment by NicholasBoll** [comment] 2020-03-05 17:48
Here's a link to the table of interaction states: https://workday.github.io/canvas-kit/?path=/story/components-buttons-button-react-visual-testing-icon-button--states

**Comment by NicholasBoll** [comment] 2020-03-05 17:56
We might be out of spec. I found this design spec: https://www.figma.com/file/GSpggBAYuivfgSkwvc4uZEBB/Buttons---Icon-Buttons?node-id=0%3A1

It does look like "Click" (I'm assuming that means "Focus") has a different background color than "Hover", but it does still have a gray background.

**Comment by aurbanski** [comment] 2020-03-05 18:07
Yeah, and I know that we have an add new component and the normal button doesn't have a darker background on focus 
![image](https://user-images.githubusercontent.com/22889346/76011082-38a90c00-5ed1-11ea-912c-0d18136e7314.png)
but for some reason the icon button does 
![image](https://user-images.githubusercontent.com/22889346/76011112-452d6480-5ed1-11ea-9d4d-ef2d3e5eb2e6.png)
And it's not using the beta button or anything. this is the import 
![image](https://user-images.githubusercontent.com/22889346/76011267-8291f200-5ed1-11ea-9d4b-80c69fc2d485.png)

**Comment by aurbanski** [comment] 2020-03-05 18:08
Neither of those are hovered

**Comment by anicholls** [comment] 2020-03-05 18:09
@aurbanski Huh - it seems you are correct! My apologies. Okay we will check in with the design team on the expected behavior and report back

**Comment by aurbanski** [comment] 2020-03-05 18:10
No problem, it's definitely not a super pressing issue either. Whenever you guys have time

**Comment by aurbanski** [comment] 2020-03-05 18:11
Thanks for responding so quickly!

**Comment by aurbanski** [comment] 2020-03-06 00:02
We definitely don't need it soon, we're doing a refactor ourselves so it won't be seen for a while. And even if we do get through that, it's definitely not gonna halt anything we're working on. It's definitely still usable. Thanks for your help!

**Comment by anicholls** [comment] 2020-04-17 16:40
Closed by #577

**Closed by anicholls** 2020-04-17 16:40 UTC
Labels: 4.x, bug, p:1
