### ISSUE TITLE
Generate stable IDs

### ISSUE THREAD

**Issue by matsprea** [Workday/canvas-kit#664] opened 2020-05-20 10:58 UTC
## 🚀 Feature Proposal

I'd like to have stable generated IDs instead of completely different at each execution.

## Motivation

As a developer I want to control these IDs and be able to use snapshots in automation to check their values. At the moment I have to mock the IDs because the ones generated by `uuid` are changing at every execution.

**Comment by lychyi** [comment] 2020-05-22 15:12
@matsprea Thanks for the issue.

Can you add a bit more context or a code block? I'm curious if mocking `uuid` causing another downstream issue for you? In the past, that's how we recommend that people do this for stable snapshots.

Also, which components are you specifically talking about? Some components have a manual id override like `FormField`. Others are ids generated as part of the component itself and they're not overridable by design.

We're not closed to the idea entirely but some more context about the pain point would help us a ton!

**Comment by matsprea** [comment] 2020-05-25 13:11
My specific issue is with the `popup` component that is generating an id for the `aria-labelledby` to reference the tittle of the popup and every time we run the automation, the id changes.

`NotificationsPopup >  › NotificationsPopup > › snapshot with open set to true

    expect(received).toMatchSnapshot()

    Snapshot name: `NotificationsPopup >  NotificationsPopup > snapshot with open set to true 1`

    - Snapshot
    + Received

    @@ -536,11 +536,11 @@
      
      <div
        class="emotion-20"
      >
        <div
    -     aria-labelledby="0f7757d3-5286-459e-9c98-28de998ca51e"
    +     aria-labelledby="58ae28cd-88d6-4158-996a-038fa8be04c7"
          aria-modal="true"
          class="emotion-19"
          role="dialog"
          tabindex="-1"
        >
    @@ -580,11 +580,11 @@
          <div
            class="emotion-18"
          >
            <h3
              class="emotion-3"
    -         id="0f7757d3-5286-459e-9c98-28de998ca51e"
    +         id="58ae28cd-88d6-4158-996a-038fa8be04c7"
            >
              Mentions (1)
            </h3>
            <div
              class="emotion-17"

      52 | export const takeSnapshot = (component, state) => {
      53 |   const { container } = getRenderedResult(component, state);
    > 54 |   expect(getTarget(container)).toMatchSnapshot();
         |                                ^
      55 | };
      56 | 
      57 | export const takeTableElementSnapshot = (component, state) => {

      at toMatchSnapshot (src/__tests__/testUtils.jsx:54:32)
      at Object.<anonymous> (src/components/common/header/notifications/popup/__tests__/NotificationsPopup.test.jsx:20:7)`

As a workaround we are mocking the Id in the test

`jest.mock('uuid/v4', () => jest.fn(() => 'theIdToTestWith'));
`

but we would like to have it generated in a predictable/stable way or control how it's generated.

**Comment by matsprea** [comment] 2020-06-04 15:42
Thanks @NicholasBoll , that will be awesome!

**Comment by NicholasBoll** [comment] 2022-01-10 17:51
Closed by #1408

**Closed by NicholasBoll** 2022-01-10 17:51 UTC
Labels: enhancement, p:1, developer-experience, documentation
