### ISSUE TITLE
Improve visual testing coverage for IconButtonToggleGroup

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#710] opened 2020-06-08 21:46 UTC
Improve coverage of snapshot tests for IconButtonToggleGroup module..

See #683

**Comment by anicholls** [comment] 2020-06-10 23:29
Since this component/story was renamed, and there are differences between the story layouts between `master` and `prerelease/v4`, automated regression will not work. Also, there were several UI bug fixes/improvements made during the move. For these reasons, testing will have to be manual. 

I did a manual review and things look good. However, I found a small bug in the story logic. Going to close this issue as there are no visual regressions, but will open a PR to fix the bug and enable snapshots on the new SegmentedControl component.

**Closed by anicholls** 2020-06-10 23:29 UTC
Labels: 4.x, testing
